{{- if (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- include "supertokens.fullname" . | indent 1 }}
  labels:
{{ include "supertokens.labels" . | indent 4}}
type: Opaque
stringData:
{{- if .Values.database.uri }}
  POSTGRESQL_CONNECTION_URI: {{ quote .Values.database.uri }}
{{- else }}
  POSTGRESQL_DATABASE_NAME: {{ quote .Values.database.name }}
  POSTGRESQL_PORT: {{ quote .Values.database.port }}
  POSTGRESQL_HOST: {{ quote .Values.database.host }}
  POSTGRESQL_USER: {{ quote .Values.database.user }}
  POSTGRESQL_PASSWORD: {{ quote .Values.database.password }}
{{- end }}
{{- if .Values.apiKeys.enabled }}
  API_KEYS: "{{ join "," .Values.apiKeys.keys }}"
{{- end }}
{{- end }}